[package]
name = "cargobomb"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]

[profile.dev]
opt-level = 0

[dependencies]
clap = "2.11.3"
error-chain = "0.10"
tempdir = "0.3.4"
url = "1.1"
walkdir = "0.1.8"
semver = "0.6"
lazy_static = "0.2"
chrono = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
flate2 = "0.2.9"
tar = "0.4.0"
toml = "0.2.1"
scopeguard = "0.3"
libc = "0.2.7"
rand = "0.3"
kernel32-sys = "0.2.2" 
winapi = "0.2.8" 
reqwest = "0.6.2"
hyper = "0.10.10"
slog = "2"
slog-scope = "3"
slog-term = "2"
tokio-core = "0.1.7"
futures = "0.1.13"
tokio-timer = "0.1.1"
tokio-process = "0.1.2"
tokio-io = "0.1.1"

[replace]
"hyper:0.10.10" = { git = "https://github.com/hyperium/hyper/", branch = "0.10.x" }
"reqwest:0.6.2" = { git = "https://github.com/tomprince/reqwest", branch = "error-for-status" }
