[package]
name = "crater"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]

[profile.dev]
opt-level = 0

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
crates-index = "0.10"
crossbeam = "0.3"
dotenv = "0.10.0"
error-chain = "0.10"
flate2 = "1"
futures = "0.1.13"
futures-cpupool = "0.1.5"
handlebars = "0.29.1"
hyper = "0.11.14"
lazy_static = "1.0"
libc = "0.2.7"
mime = "0.3.1"
petgraph = "0.4.11"
rand = "0.3"
ref_slice = "1.1.1"
reqwest = "0.8"
rusoto_core = "0.31.0"
rusoto_s3 = "0.31.0"
rustup-dist = { git = "https://github.com/rust-lang-nursery/rustup.rs", tag="1.7.0" }
scopeguard = "0.3"
semver = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_regex = "0.1.0"
slog = "2"
slog-scope = "4"
slog-term = "2"
structopt = "0.1.0"
structopt-derive = "0.1.0"
tar = "0.4.0"
tempdir = "0.3.4"
tempfile = "3.0.0"
tokio-core = "0.1.7"
tokio-io = "0.1.1"
tokio-process = "0.1.2"
tokio-timer = "0.1.1"
toml = "0.4.1"
url = "1.1"
walkdir = "2"
regex = "0.2.10"
ring = "0.12.1"
rusqlite = { version = "0.13.0", features = ["chrono"] }
r2d2 = "0.8.2"
r2d2_sqlite = "0.5.0"
base64 = "0.9.0"
