[bot]
webhooks-secret = ""
api-token = ""

[reports-bucket]
# This is configured by default to use the public minio playground
# S3 can be changed by setting the region name (for example "us-east-1")
region = ["custom", "https://play.minio.io:9000"]
bucket = "crater-reports"
public-url = "https://play.minio.io:9000"
access-key = "Q3AM3UQ867SPQQA43P2F"
secret-key = "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"

[agents]
# "TOKEN" = "agent-name"
